
language: go
go_import_path: github.com/maxatome/go-testdeep

sudo: false

matrix:
  include:
    - go: 1.13.x
    - go: 1.14.x
      env:
        - GO_TEST_SAFE_FLAGS="-covermode=atomic -coverprofile=coverage-safe.out ./..."
        - GO_TEST_UNSAFE_FLAGS="-covermode=atomic -coverprofile=coverage-unsafe.out ./..."
        - USE_LINTER=1
      install:
        - wget -O - -q https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $GOPATH/bin v1.21.0
      after_success:
        - go get github.com/mattn/goveralls
        - goveralls -coverprofile=coverage.out -service=travis-ci
    - go: master
  allow_failures:
    - go: master
  fast_finish: true

script:
  - export GORACE="halt_on_error=1"
  - go get -t ./...
  - go test -race -tags safe $GO_TEST_SAFE_FLAGS ./...
  - go test -race $GO_TEST_UNSAFE_FLAGS ./...
  - >
    [ "$USE_LINTER" != 1 ] ||
      golangci-lint run -E gofmt -E golint -E maligned -E misspell -E prealloc -E unconvert -E whitespace -E goimports ./...